// This game is a guided projected that will be based on the tic tac toe game 
#include <iostream>

using namespace std;

int main() {

// think of board representation first( create a board and initialize it)

char board[3][3];

// find out how to display board

// find out player moves (turn logic)

// Find out how to do win checking (logic for win or lose)

// Find out how to do game loop (replay logic)


return 0;
}
